#!/usr/bin/env bash
# Pings an IP address received as a string argument 5 times.
# $# is used in bash to check num of commandline arg passed.
# $1 is commandline arg 1
# $2 is commandline arg 2 ....

if [ "$#" -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
