#!/usr/bin/env bash
# write a Bash script that accepts one argument
# script should run the whoami command under the user passed as an argument

if [ $# -ne 1 ]; then
	echo "Usage: $0 <user>"
	exit 1
fi
sudo -u "$1" whoami
