#!/usr/bin/env bash
# Reload Gunicorn in a graceful way

PROCESS_NAME="gunicorn"

# Find the PID of the Gunicorn master process
PID=$(pgrep -f "^${PROCESS_NAME}")

if [ -z "$PID" ]; then
    echo "No process found for $PROCESS_NAME"
    exit 1
fi

# Send the HUP signal to gracefully reload Gunicorn
kill -HUP "$PID"

# Check if the kill command was successful
if [ $? -eq 0 ]; then
    echo "OK"
else
    echo "NOk"
    exit 1
fi
