#!/usr/bin/env bash
# Reload Gunicorn in a graceful way

PROCESS_NAME="gunicorn"

PID=$(pgrep -f "^${PROCESS_NAME}")

if [ -z "$PID" ]; then
    echo "No process found for $PROCESS_NAME"
    exit 1
fi

kill -HUP "$PID"

if [ $? -eq 0 ]; then
    echo "OK"
else
    echo "NOk"
    exit 1
fi
